# Generated by Django 5.1.2 on 2025-03-09 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='agents/')),
            ],
        ),
        migrations.CreateModel(
            name='Annonces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnoncePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces/')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='big_transport_app.annonces')),
            ],
        ),
        migrations.AddField(
            model_name='annonces',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='big_transport_app.categories'),
        ),
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu / Quartier')),
                ('phone', models.CharField(max_length=30, verbose_name='Numéro de téléphone')),
                ('choix_principal', models.CharField(choices=[('type_camion', 'Type de camion'), ('nombre_cubage', 'Nombre de cubage')], max_length=20, verbose_name='Choix principal')),
                ('camion_type', models.CharField(blank=True, help_text="Spécifier si le choix principal est 'Type de camion'", max_length=50, null=True, verbose_name='Type de camion')),
                ('nombre_voyage', models.PositiveIntegerField(blank=True, max_length=1000000, null=True, verbose_name='Nombre de voyage')),
                ('nombre_cubage', models.PositiveIntegerField(blank=True, default=0, help_text="Spécifier si le choix principal est 'Nombre de cubage", null=True, verbose_name='Nombre de cubage')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='big_transport_app.annonces', verbose_name='Annonce associée')),
            ],
        ),
    ]
