# Generated by Django 5.1.2 on 2024-12-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_transport_app', '0002_produits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commander',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu / Quartier')),
                ('phone', models.CharField(max_length=30, verbose_name='Numéro de téléphone')),
                ('choix_principal', models.CharField(choices=[('type_camion', 'Type de camion'), ('nombre_cubage', 'Nombre de cubage')], max_length=20, verbose_name='Choix principal')),
                ('camion_type', models.CharField(blank=True, help_text="Spécifier si le choix principal est 'Type de camion'", max_length=50, null=True, verbose_name='Type de camion')),
                ('nombre_cubage', models.PositiveIntegerField(blank=True, help_text="Spécifier si le choix principal est 'Nombre de cubage'", null=True, verbose_name='Nombre de cubage')),
            ],
        ),
    ]
