# Generated by Django 5.1.2 on 2025-02-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_transport_app', '0003_commander'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
