# Generated by Django 5.1.2 on 2025-02-28 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_transport_app', '0005_annonces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='photos',
        ),
        migrations.CreateModel(
            name='AnnoncePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces/')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='big_transport_app.annonces')),
            ],
        ),
    ]
