# Generated by Django 5.1.2 on 2025-03-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('big_transport_app', '0006_remove_annonces_photos_annoncephoto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produits',
        ),
    ]
