# Generated by Django 5.1.2 on 2025-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_transport_app', '0007_delete_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='commander',
            name='nombre_voyage',
            field=models.PositiveIntegerField(default=1, max_length=1000000, verbose_name='Nombre de voyage'),
            preserve_default=False,
        ),
    ]
